name: Publish package

on:
  push:
    tags: ['*']

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: npm
      url: https://www.npmjs.com/package/jsonresume-theme-relaxed
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up NodeJS
        uses: actions/setup-node@v5
        with:
          node-version: '24'
          registry-url: https://registry.npmjs.org/
      - name: Install packages
        run: npm ci
      - name: Publish to NPM
        run: npm publish --provenance
